dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "igorpelevanyuk-github"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
notifications:
  email: false
