dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "lUFIP2gU3UAtN5iNRyK3N+7KdpvzyhHJD7+LKx1zsZIFIEsOHCjiSia03K/ihvQ4MYPI7NA94XS0fZXHk09kreci/5sLL1zCvOjwTCBFSaZVkP86kOJDgn0hVA2hsB52nOt0WFp7gyFmWnyrdF96sP9Zo3KHsgNrGhlnNY588rpf6Fed8fRTjgt95uALzngKBwu3aTMoHZVxu93o3WRTlkOxlaG8CpmZv+Ny/Ocfp4PNllQDhuILSfaykAuGD1GLhDgIrZbHvQM1LV6c4/tKy39q/7kGneBNsqj2O2z9YCU8wamnsEs8zIi4hRKRlQUMFQx3ZNYI0dbax7RrCmR6JI5hBxB5KOIAMB0Hq5s+mGmk4HmKmU1qmp88t9nzWgVol2gsNcT4RmfV7HV/G1Jzxw7MDL6owv2n7uuH7RSKAQGRvDFP0/qRYYw8L4QQJXiBvpCyzGNV8ie0007xwcBFX/I1cZMGovWSBxXKXHWZSsqXtslrY5ooVfbZScw61a9USGUkZ6dXZ8O2U/N+f+9GxpA5BEZ4Rkwqlzei736AuZTLXn1T2C8i+/WVt2tApw6STlk+uInmfJWYWhd5r/Jd5rCXRTwD9WU5/u7XNEYL3C7KooQCB/JvI3+MhTJqJzdeR/LNITxJ3kGJeeq8+t7m3snWsoVlndoeA30y59Z00II="

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
notifications:
  email: false
